"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
indicates settings and configuration for your project and contains
initial default settings.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-hhp)$_do#t)zoafow%6k$c921&qc2m8ge18d3zpifzu^^k4*th'


"""DEBUG is a Boolean that turns the debug mode of the project on and off. If it is set to True, Django
will display detailed error pages when an uncaught exception is thrown by your application.
When you move to a production environment, remember that you have to set it to False.
Never deploy a site into production with DEBUG turned on because you will expose sensitive
project-related data."""
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

"""ALLOWED_HOSTS is not applied while debug mode is on or when the tests are run. Once you
move your site to production and set DEBUG to False, you will have to add your domain/host
to this setting to allow it to serve your Django site."""
ALLOWED_HOSTS = []

"""INSTALLED_APPS is a setting you will have to edit for all projects. This setting tells Django which
applications are active for this site."""

SITE_ID = 1

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin', #administration site
    'django.contrib.auth', #authentication framemework
    'django.contrib.contenttypes', #a framework for handlng content types
    'django.contrib.sessions', #session framework
    'django.contrib.messages', #messaging framework
    'django.contrib.staticfiles', # a framework for managing static files
    'blog.apps.BlogConfig',#application configuration
    'taggit',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.postgres'

]

# a list that contains middleware to be executed
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

#indicates the Python module where the root URL patterns of your application are defined.
ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'

"""DATABASES is a dictionary that contains the settings for all the databases to be used in the project.
There must always be a default database. The default configuration uses an SQLite3 database."""
# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME':'blog',
        'USER' :'carol',
        'PASSWORD':'12345'
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/
#defines the default language code for this Django site
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

#STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

#MEDIA_URL = '/media/'
#MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email server configuration
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'carolgitongaofficial@gmail.com'
EMAIL_HOST_PASSWORD = 'zlgnyqsskdphjqzg'
EMAIL_PORT = 587
EMAIL_USE_TLS = True